name: Terraform

permissions:
  id-token: write
  contents: write
  issues: write
  pull-requests: write

on:
  workflow_call:
    inputs:
      iam_role:
        required: true
        type: string

jobs:
  aws:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: eu-central-1
          role-to-assume: ${{ inputs.iam_role }}
          role-session-name: withlogicco-workflows-tf-${{ github.run_id }}
      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.2.x
      - run: terraform init
      - run: terraform fmt -recursive -check
      - run: terraform validate
      - run: terraform plan -input=false -out=tf-plan
      - name: show-plan
        if: github.event_name == 'pull_request'
        id: plan
        run: terraform show -no-color tf-plan
      - if: github.event_name == 'pull_request'
        uses: actions/github-script@0.9.0
        env:
          PLAN: "${{ steps.plan.outputs.stdout }}"
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const output = `#### Terraform Plan 📖

            <details><summary>Show Plan</summary>

            \`\`\`${process.env.PLAN}\`\`\`

            </details>

            *Pusher: @${{ github.actor }}*`;

            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })
      - if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: terraform apply -input=false tf-plan
